### ISSUE TITLE
Cloudinary GUI panel is no input fields

### ISSUE THREAD

**Issue by jamesgrubb** [tdatu/cloudinary_exporter#1]
HI. Thank you for the plugin. I'm having an issue.  I'm on Blender 3.6.4. I installed the plugin. The Cloudinary tab shows up but on click it simply displays the words Cloudinary but there are no form inputs to add Cloudinary info? Thanks in advance.

**Comment by tdatu** [comment]
@jamesgrubb, it should be fixed now.  Let me know if there's still an issue.

**Comment by tdatu** [comment]
Closing, this is fix.
